# Generated by Django 4.2.9 on 2025-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pago', '0002_remove_pedidoitem_producto_pedidoitem_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='external_id',
            field=models.IntegerField(blank=True, help_text='ID del pedido en el sistema remoto', null=True),
        ),
    ]
