# Generated by Django 3.1 on 2024-10-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_camisetas', '0002_cargar_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='talla',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
