# Generated by Django 3.1 on 2024-10-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_camisetas', '0003_pedidoitem_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='talla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
