# Generated by Django 3.1 on 2024-11-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_camisetas', '0005_direccionenvio_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='direccion_envio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='pedidoitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='DireccionEnvio',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='PedidoItem',
        ),
    ]
